# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-comet.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/comet


include vendor/pixeloverlays/comet/overlays.mk
