PRODUCT_PACKAGES += \
    AvatarPickerPixelOverlay \
    BiometricCometOverlay \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FaceEnrollCometOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PearlOverlay2024 \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    PixelDisplayServiceOverlay \
    PixelSetupWizardOverlay2024 \
    PixelSetupWizardOverlayPixelFoldable2024 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleCometOverlay \
    SettingsGoogleCometOverlayRRO \
    SettingsProviderCometOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGoogleCometOverlayVendorRRO \
